eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10001
spring:
  application:
    name: common-gateway-api
zuul:
  routes:
    api-service-user-center:
      path: /user/**
      serviceId: service-user-center